# Generated by Django 4.2.11 on 2024-09-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authors',
        ),
    ]
